# Generated by Django 2.1.5 on 2019-09-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo_slider', models.ImageField(upload_to='products/%Y/%m/%d')),
                ('photo_main', models.ImageField(blank=True, upload_to='products/%Y/%m/%d')),
            ],
        ),
    ]
