# Generated by Django 2.1.5 on 2019-09-08 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='photo_slider',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d'),
        ),
    ]
